added Glyma gnm1 repeats
legumeinfo/datastore-registry pull request #4
Opened 2023-11-03 21:13 UTC by jd-campbell

This is my first time using this so I want to make sure I did this right. 

I added Glycine max repeats from gnm1 from SoyBase Classic (SoyTEdb).

2023-11-06 15:24 UTC, StevenCannon-USDA requested changes
A minor change to make before approving (see comments linked to the changed file).

2023-11-06 15:24 UTC, StevenCannon-USDA commented on ds_registry.tsv
A small change: `repeats Wm82.rpt` rather than `repeats Wm82.rpt1`

You can make this change by editing the ds_registry.tsv file directly.

The reason: we are using a version number for the "type" only for the genome and annotation (`gnm1`, `ann1`).

Precedents:
```
grep rpt ds_registry.tsv 
SHSZ	Arachis	GENUS	repeats	mixed.rpt
XJGZ	Arachis	GENUS	repeats	mixed.rpt
931Q	Arachis	cardenasii	repeats	K10017.rpt
GZZS	Arachis	hypogaea	repeats	Tifrunner.rpt
```
The data would go into `Glycine/max/repeats/Wm82.rpt.C1JW`

... unless the repeats were species-wide or genus-wide. In the genus case, they would go into a collection in `Glycine/GENUS`
... but I think in this case, the repeats have coordinates with respect to Wm82 assembly 1, so it would be appropriate to put them in a collection labeled with `Wm82`.

2023-11-09 22:53 UTC, jd-campbell commented on ds_registry.tsv
I have made that change. Thank you for the help. I know I will be asking you more Data Store questions later.

2023-11-09 22:57 UTC, merged

2023-11-09 22:57 UTC, jd-campbell commented
The requested change was made.